---
- name: Checkout code from Git
  hosts: all
  tasks:
    - name: Ensure git is installed
      yum:
        name: git
        state: present

    - name: Checkout code from repository
      git:
        repo: "https://github.com/choudharysumit150/hello-world.git"
        dest: "/opt/jenkinsAgent"
        version: "ansibleHost"
